import { View, Text } from 'react-native';

interface PreRoundPlaybookCardProps {
  playerName?: string;
  courseName: string;
  teeName: string;
  par: number;
  goal: number;
  preRoundTalk?: string;
  topHoles?: Array<{
    hole: number;
    par: number;
    keyTip: string;
  }>;
}

/**
 * Pre-round playbook card for sharing.
 * Shows the game plan before heading to the course.
 * 1080x1920px portrait format.
 */
export function PreRoundPlaybookCard({
  playerName,
  courseName,
  teeName,
  par,
  goal,
  preRoundTalk,
  topHoles,
}: PreRoundPlaybookCardProps) {
  return (
    <View className="bg-green-deep p-8 items-center justify-center" style={{ minHeight: 800 }}>
      {/* Header */}
      <Text className="text-sm tracking-[4px] uppercase text-gold font-bold mb-2">
        Game Plan
      </Text>

      {/* Course Info */}
      <Text className="text-3xl text-white font-bold mb-1" style={{ fontFamily: 'serif' }}>
        {courseName}
      </Text>
      <Text className="text-lg text-cream-dim mb-6">
        {teeName} Tees · Par {par}
      </Text>

      {/* Player Info */}
      {playerName && <Text className="text-base text-cream mb-6">{playerName}</Text>}

      {/* Goal */}
      <View className="bg-gold/10 rounded-lg px-6 py-4 mb-8 w-full items-center">
        <Text className="text-xs text-cream-dim mb-1">Today's Goal</Text>
        <Text className="text-4xl text-gold font-bold" style={{ fontFamily: 'serif' }}>
          {goal}
        </Text>
      </View>

      {/* Pre-Round Talk */}
      {preRoundTalk && (
        <View className="mb-8 bg-gold/5 border border-gold/20 rounded-lg p-5 w-full">
          <Text className="text-xs tracking-[2px] uppercase text-gold font-bold mb-3">
            Mental Keys
          </Text>
          <Text className="text-base text-cream leading-6">{preRoundTalk}</Text>
        </View>
      )}

      {/* Key Holes */}
      {topHoles && topHoles.length > 0 && (
        <View className="w-full mb-8">
          <Text className="text-xs tracking-[2px] uppercase text-gold font-bold mb-3">
            Critical Holes
          </Text>
          {topHoles.map((hole, idx) => (
            <View
              key={idx}
              className="mb-3 p-3 bg-gold/5 border border-gold/10 rounded-lg flex-row gap-3"
            >
              <View className="w-12 items-center justify-center bg-gold/20 rounded">
                <Text className="text-xl text-gold font-bold">#{hole.hole}</Text>
              </View>
              <View className="flex-1 justify-center">
                <Text className="text-xs text-cream-dim mb-1">Par {hole.par}</Text>
                <Text className="text-sm text-cream">{hole.keyTip}</Text>
              </View>
            </View>
          ))}
        </View>
      )}

      {/* Footer CTA */}
      <View className="w-full mt-auto pt-6 border-t border-gold/20">
        <Text className="text-center text-sm text-cream-dim mb-3">
          Generated by AI Caddie
        </Text>
        <Text className="text-center text-lg font-bold text-gold">
          Let's Break 90 Today
        </Text>
      </View>
    </View>
  );
}
